name: Versioned and Stable Release

on:
  push:
    branches:
      - 'v*'

jobs:
  create-release:
    name: Create and push docker image and releases
    if: github.repository == 'kubearmor/kubearmor-relay-server'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push images to Docker
        run: ./relay-server/build/push_img.sh

      # Create versioned release using the branch name
      - name: Create Versioned Release
        id: create-versioned-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: Versioned release for ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Create stable release using stable-<branch_name> as the tag
      - name: Create Stable Release
        id: create-stable-release
        uses: actions/create-release@v1
        with:
          tag_name: stable
          release_name: Release stable-${{ github.ref_name }}
          body: Stable release for ${{ github.ref_name }}
          draft: false
          prerelease: false

